[package]
name = "bilrost"
version = "0.1015.0"
authors = [
    "Kent Ross <k@mad.cash>",
]
license = "Apache-2.0"
repository = "https://github.com/mumbleskates/bilrost"
documentation = "https://docs.rs/bilrost"
readme = "README.md"
description = "A compact protobuf-like serializer and deserializer for the Rust Language."
keywords = ["serialization", "no-std", "derive", "encoding"]
categories = ["encoding", "no-std"]
edition = "2021"
resolver = "2"
rust-version = "1.65"

[workspace]
members = ["bilrost-derive"]

[dependencies]
arrayvec = { version = ">=0.6.0,<0.8", default-features = false, optional = true }
bilrost-derive = { version = "=0.1015.0", path = "bilrost-derive" }
bytes = { version = "^1", default-features = false }
tinyvec = { version = "^1", default-features = false, features = ["alloc", "rustc_1_57"] }

[features]
derive = []
std = []
